### ISSUE TITLE
Confusing deprecatin warning: `/usr/bin/jsonschema:5: DeprecationWarning: The jsonschema CLI is deprecated`

### ISSUE THREAD

**Issue by hoijui** [sourcemeta/jsonschema#205]
I just compiled latest `main` branch, and when running `jsonchema -h`, I get:

```text
/usr/bin/jsonschema:5: DeprecationWarning: The jsonschema CLI is deprecated and will be removed in a future version. Please use check-jsonschema instead, which can be installed from https://pypi.org/project/check-jsonschema/
  from jsonschema.cli import main
usage: jsonschema [-h] [-i INSTANCES] [-F ERROR_FORMAT] [-o {plain,pretty}] [-V VALIDATOR] [--base-uri BASE_URI] [--version] schema

JSON Schema Validation CLI

positional arguments:
  schema                the path to a JSON Schema to validate with (i.e. schema.json)

options:
  -h, --help            show this help message and exit
...
```

At first glance, I though this tool is deprecated, and started looking for the mentioned alternative "check-jsonschema".
But looking qt your GitHub again, it felt strange that there is no deprecation warning and it seems to be still actively developed, so I read the error message again, and figured that this (C++) tool uses a python library that is also called `jsonschema`, and that only *that* is deprecated.
Would it be possible to switch to that mentioned alternative, or at least suppress this message?

**Comment by hoijui** [comment]
woops! :D
I actually ran the wrong tool (it came before in my PATH). Sorry!

**Comment by jviotti** [comment]
No worries and glad you figured it out :) Any feedback on the CLI would be more than appreciated!

**Comment by hoijui** [comment]
I use the `lint` and `fmt` commands; excellent! :-)
I also tried `identify`, and found that it still shows the old project URL! so that one also helped.
I tried `fragment`, and was confused about the _in-place_ in its description: "Frame a schema in-place". I though it will overwrite the schema (kind of like reformat), but it does not.
I have not tried `bundle` yet, but I might do so in the future, if I'll start using external schemas. Same with `test` and `validate`.

I searched for a linter only, and from all I saw, this one looked most promising, and it has a lot of other cool possibilities!
Being able to maintain schemas in a neat way (ensuring correctness, minimizing diffs, ...) is an important part of modern digital infrastructure, so I hope this tool gets used extensively.
Thanks for it!

**Comment by jviotti** [comment]
> I also tried identify, and found that it still shows the old project URL! so that one also helped.

What do you mean by the old project URL?

> and was confused about the in-place in its description: "Frame a schema in-place". I thought it will overwrite the schema (kind of like reformat), but it does not.

Ah, great feedback. Fixing it here: https://github.com/sourcemeta/jsonschema/pull/206

> I searched for a linter only, and from all I saw, this one looked most promising, and it has a lot of other cool possibilities!
Being able to maintain schemas in a neat way (ensuring correctness, minimizing diffs, ...) is an important part of modern digital infrastructure, so I hope this tool gets used extensively.

Thank a lot! We are still heavily growing our set of linter rules, so I you have ideas (with before/after examples), please don't hesitate to suggest them, or if you feel like attempting to contribute some rules, they are implemented here: https://github.com/sourcemeta/alterschema/tree/main/src/linter

**Comment by hoijui** [comment]
> > I also tried identify, and found that it still shows the old project URL! so that one also helped.
> 
> What do you mean by the old project URL?

I mean the schema URL of my own schema. The hosting URL changed, and I did not update the ID in the file.
> 
> > and was confused about the in-place in its description: "Frame a schema in-place". I thought it will overwrite the schema (kind of like reformat), but it does not.
> 
> Ah, great feedback. Fixing it here: #206

Thank you!

> 
> > I searched for a linter only, and from all I saw, this one looked most promising, and it has a lot of other cool possibilities!
> > Being able to maintain schemas in a neat way (ensuring correctness, minimizing diffs, ...) is an important part of modern digital infrastructure, so I hope this tool gets used extensively.
> 
> Thank a lot! We are still heavily growing our set of linter rules, so I you have ideas (with before/after examples), please don't hesitate to suggest them, or if you feel like attempting to contribute some rules, they are implemented here: https://github.com/sourcemeta/alterschema/tree/main/src/linter

ahh nice! :-)
Will do, If something comes to mind!

**Comment by jviotti** [comment]
> I mean the schema URL of my own schema. The hosting URL changed, and I did not update the ID in the file.

Nice! What schemas are you hosting btw? In which form? Asking as I'm planning to develop more foundational technologies for schema hosting, etc. Would love to learn more about what your requirements are or what would make for a great i.e. hostable OSS service.
